/*
 * @Author: 卢勇其
 * @Date: 2020-06-11 22:27:12
 * @LastEditors: your name
 * @LastEditTime: 2020-06-13 16:17:30
 * @Description: file content
 */ 

import {
    Login,
    NotFound,
    Home,
    AddArticle,
    EditArticle,
    ArticleCategory,
    ArticleList,
    Tags,
    Comment,
    CarouselAd,
    PhotosCategory,
    PhotosUpload,
    PhotosLook,
    AboutMe,
    AccountManage,
    RemarkManage,
    LogManage,
    LinkManage,
    UserManage,
    RoleManage,
    MenuManage
} from '../Pages'

import {
    DesktopOutlined,
    PieChartOutlined,
    FileOutlined,
    TeamOutlined,
    UserOutlined,
  } from '@ant-design/icons';        //icon图标组件

export const mainRouter = [
    {
        pathname:'/login',
        component:Login
    },{
        pathname:'/404',
        component:NotFound
    },
]

export const adminRouter = [
    {
        pathname:'/admin/home',
        component:Home,
        title:'工作台',
        exact:true,
        isNav:true,
        icon:DesktopOutlined
    },{
        pathname:'/admin/article',
        exact:true,
        title:'文章管理',
        isNav:true,
        icon: PieChartOutlined,
        children:[
            {
                pathname:'/admin/article/add',
                component:AddArticle,
                title:'添加文章',
                icon:'profile',
            },
            {
                pathname:'/admin/article/edit',
                component:EditArticle,
                title:'编辑文章',
                icon:'profile',
            },
            {
                pathname:'/admin/article/list',
                component:ArticleList,
                title:'文章列表',
                icon:'profile',
            },
            {
                pathname:'/admin/article/category',
                component:ArticleCategory,
                title:'分类管理',
                icon:'profile',
            },
            {
                pathname:'/admin/article/tags',
                component:Tags,
                title:'标签管理',
                icon:'profile',
            },
            {
                pathname:'/admin/article/comment',
                component:Comment,
                title:'评论管理',
                icon:'profile',
            },
        ]
    },{
        pathname:'/admin/ad',
        component:CarouselAd,
        title:'轮播广告',
        exact:false,
        isNav:true,
        icon:FileOutlined
    },{
        pathname:'/admin/photos',
        title:'相册管理',
        exact:true,
        isNav:true,
        icon:TeamOutlined,
        children:[
            {
                pathname:'/admin/photos/category',
                component:PhotosCategory,
                title:'相册分类',
                icon:'profile',
            },
            {
                pathname:'/admin/photos/upload',
                component:PhotosUpload,
                title:'相册上传',
                icon:'profile',
            },
            {
                pathname:'/admin/photos/look',
                component:PhotosLook,
                title:'相册查看',
                icon:'profile',
            },
        ] 
    },{
        pathname:'/admin/personal',
        component:AboutMe,
        title:'个人资料',
        isNav:true,
        icon:UserOutlined
    },{
        pathname:'/admin/account',
        component:AccountManage,
        title:'账号管理',
        isNav:true,
        icon:UserOutlined
    },{
        pathname:'/admin/remark',
        component:RemarkManage,
        title:'留言管理',
        isNav:true,
        icon:UserOutlined
    },{
        pathname:'/admin/log',
        component:LogManage,
        title:'日志管理',
        isNav:true,
        icon:UserOutlined
    },{
        pathname:'/admin/link',
        component:LinkManage,
        title:'友情链接',
        isNav:true,
        icon:UserOutlined
    },{
        pathname:'/admin/sys',
        title:'系统管理',
        exact:true,
        isNav:true,
        icon:UserOutlined,
        children:[
            {
                pathname:'/admin/sys/user',
                component:UserManage,
                title:'用户管理',
                icon:'profile',
            },
            {
                pathname:'/admin/sys/role',
                component:RoleManage,
                title:'角色管理',
                icon:'profile',
            },
            {
                pathname:'/admin/sys/menu',
                component:MenuManage,
                title:'菜单管理',
                icon:'profile',
            },
        ] 
    }

]